-- 03_postgresql_compras.sql
-- Tablas para la "tercera fuente" (compras de insumos/equipamiento)

SET search_path TO gestion, public;

-- ==================== DISTRIBUIDORES/PROVEEDORES ====================
CREATE TABLE distribuidor (
    codigo_distribuidor VARCHAR(10) PRIMARY KEY,
    distribuidor VARCHAR(120) NOT NULL,
    ruc VARCHAR(13),
    ciudad VARCHAR(80),
    contacto_ventas VARCHAR(100),
    cargo VARCHAR(80),
    telefono VARCHAR(20),
    correo VARCHAR(120),
    condicion_pago VARCHAR(50),
    tiempo_entrega_estimado VARCHAR(50),
    descuento_base DECIMAL(5,2),
    lineas_laboratorio VARCHAR(200)
);

-- ==================== PRODUCTOS_REFERENCIA ====================
CREATE TABLE producto_referencia (
    codigo_producto VARCHAR(15) PRIMARY KEY,
    producto VARCHAR(120) NOT NULL,
    categoria VARCHAR(80),
    proveedor VARCHAR(100),
    presentacion VARCHAR(80),
    costo_base DECIMAL(10,2),
    precio_venta DECIMAL(10,2),
    margen_referencial DECIMAL(5,2)
);

-- ==================== COMPRAS ====================
CREATE TABLE compra (
    id_compra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_compra DATE NOT NULL,
    orden_compra VARCHAR(20) NOT NULL,
    factura_distribuidor VARCHAR(30),
    lote_compra VARCHAR(30),
    codigo_distribuidor VARCHAR(10) REFERENCES distribuidor(codigo_distribuidor),
    codigo_producto VARCHAR(15) REFERENCES producto_referencia(codigo_producto),
    cantidad_cajas INTEGER,
    unidades_por_caja INTEGER,
    cantidad_unidades INTEGER,
    precio_lista_unitario DECIMAL(10,2),
    descuento_distribuidor DECIMAL(5,2),
    valor_descuento DECIMAL(10,2),
    costo_unitario_neto DECIMAL(10,2),
    total_compra_neto DECIMAL(12,2),
    codigo_sucursal_entrega VARCHAR(10) REFERENCES sucursal(codigo_sucursal),
    estado_compra VARCHAR(20) DEFAULT 'Recibido',
    condicion_pago VARCHAR(50),
    observacion VARCHAR(200)
);

-- Índices
CREATE INDEX idx_compra_fecha ON compra(fecha_compra);
CREATE INDEX idx_compra_producto ON compra(codigo_producto);
CREATE INDEX idx_compra_distribuidor ON compra(codigo_distribuidor);